**Tes crawl data twitter menggunakan tweet-harvest**
===
---

Disini saya menggunakan **tweet-harvest** milik [helmisatria](https://helmisatria.com/blog) yang berbasis Python dan Node.Js

# Twitter Auth Token

**Auth Token** *bisa diambil dari Inspec website twitter dan cari column Cookies*

**bentuk Auth Token seperti ini:** `5c566a0a301106bb9d4588ce58ce26f39ee1dxxx`

**log-in** twitter / X > buka Halaman **home** > klik kanan > klik **inspect**  

(**Chromium** : ada di aplication)

<img src="image.png" width="354" height="480"> 

pilih auth_token > lalu copy paste

(**Firefox** : ada di storage)

<img src="image-2.png" width="392" height="480"> 

pilih auth_token > lalu copy paste

In [ ]:
twitter_auth_token = '5c566a0a301106bb9d4588ce58ce26f39ee1xxx' # auth token

# Import required Python package
`!pip install pandas` 
>pandas digunakan untuk membaca **file.CSV** yang di generate saat melakukan Crawl Data 

## Install Node.js (because tweet-harvest built using Node.js)
- `!sudo apt-get update`
- `!sudo apt-get install -y ca-certificates curl gnupg`
- `!sudo mkdir -p /etc/apt/keyrings`
- `!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg`

- `!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list`

- `!sudo apt-get update`
- `!sudo apt-get install nodejs -y`

- `!node -v`
>nodejs **wajib** di install dikarenakan **tweet-harvest** di buat menggunakan nodejs dan versi nodejs paling minimum adalah ***versi 2.6.0***

In [2]:
# Import mambutuhkan Python package dan mengecek versi nodejs
!pip install pandas
!node -v

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
v22.18.0

Crawl data twitter menggunakan Tweet-Harvest
===


`filename = 'FERRY_IRWANDI.csv'`

filename merupakan layout penamaan [filename].csv

`search_keyword = 'ferry irwandi since:2025-01-01 until:2025-05-01 lang:id'`

merupakan keyword pencarian di Twitter / X dengan layout :
[Topik yang dicari] [batas tanggal awal data yang dicari] [batas tanggal akhir data yang dicari] [bahasa dari topik yang sedang di cari]

`limit = 100`

merupakan jumlah limit pencarian yang akan di ambil (kadang bisa lebih beberapa dari limit) 

`!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}`

script untuk menjalankan sistem tweet-harvest yang berbasis Nodejs

In [5]:
# Crawl Data

filename = "TUNTUTAN_RAKYAT.csv"
search_keyword = "17+8 TUNTUTAN RAKYAT since:2025-09-01 until:2025-09-05 lang:id"
limit = 1500

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/TUNTUTAN_RAKYAT.csv, renaming to ./tweets-data/TUNTUTAN_RAKYAT.old.csv

-- Scrolling... (1)
Filling in keywords: 17+8 TUNTUTAN RAKYAT since:2025-09-01 until:2025-09-05 lang:id

 (2)

Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 20

-- Scrolling... (1)

Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 40


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 60


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 80


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 100


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 120

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 140


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 160


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 180


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 200


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 220


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 240

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 260


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 280


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 297


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 317


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 337


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 357

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 377


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 396


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 416


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 436


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 453


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 473

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 493


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 513


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 530


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 550


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 570


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 590

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 610


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 630


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 650


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 670


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 690


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 710

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 730


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 750


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 770


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 790


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 810


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 830

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 850


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 870


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 890


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 910


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 930


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 950

--Taking a break, waiting for 10 seconds...


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 970


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 990


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 1010


Your tweets saved to: d:\RAHASIA\GitHub\crawl-data-twitter-menggunakan-tweet-harvest\tweets-data\TUNTUTAN_RAKYAT.csv
Total tweets saved: 1027

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 1027 tweets, done scrolling...

[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

Menampilkan data .CSV menjadi DataFrame
===

In [6]:
import pandas as pd

# jelaskan lokasi file ke CSV file
file_path = f"tweets-data/{filename}"

# mambaca CSV file ke pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# menampilkan DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1963752713256395127,Thu Sep 04 23:55:06 +0000 2025,0,Dari sekian banyak bahasan 17+8 tuntutan rakya...,1963752713256395127,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/196375271325639...,1059593600,NaN
1,1963751829935993247,Thu Sep 04 23:51:35 +0000 2025,2,Hari ini deadline 17+8 tuntutan rakyat #KawalS...,1963751829935993247,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/196375182993599...,1856170626563891200,NaN
2,1963744711740686806,Thu Sep 04 23:23:18 +0000 2025,16,ngerayain ultah pas deadline indo dengan tuntu...,1963744711740686806,https://pbs.twimg.com/media/G0CfZv5acAEyS2M.jpg,NaN,in,NaN,2,57,0,https://x.com/undefined/status/196374471174068...,1868280869448003584,NaN
3,1963741023383032065,Thu Sep 04 23:08:39 +0000 2025,2,17+8 itu apa toh? Ini bener ya? Kok gak ada 'a...,1963741023383032065,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/196374102338303...,57574639,NaN
4,1963630999398404450,Thu Sep 04 23:02:35 +0000 2025,0,@imwinteoa Ini tanda tangan bahwa dokumen yg b...,1963739496064888995,NaN,imwinteoa,in,NaN,0,0,0,https://x.com/undefined/status/196373949606488...,1603283936091656192,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,1962314858860511538,Mon Sep 01 00:41:35 +0000 2025,0,17 + 8 tuntutan rakyat itu tadi lewat English ...,1962314858860511538,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/196231485886051...,4894329029,NaN
1023,1962313342175105389,Mon Sep 01 00:35:33 +0000 2025,89,17 + 8 TUNTUTAN RAKYAT Bukan sekadar angka tap...,1962313342175105389,https://pbs.twimg.com/media/GzuJlK5bgAAkzUP.jpg,NaN,in,NaN,1,2,91,https://x.com/undefined/status/196231334217510...,1864173068589125633,NaN
1024,1962310269100855772,Mon Sep 01 00:23:20 +0000 2025,2,my birthday wish? 17 + 8 tuntutan rakyat terwu...,1962310269100855772,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/196231026910085...,1839985636759220224,NaN
1025,1962309546778763713,Mon Sep 01 00:20:28 +0000 2025,1,17 + 8 Tuntutan Rakyat @prabowo kapan lagi dib...,1962309546778763713,https://pbs.twimg.com/media/GzuGH-naUAA9_4_.jpg,NaN,in,NaN,0,1,1,https://x.com/undefined/status/196230954677876...,1676397814920925187,NaN
1026,1962306655817003157,Mon Sep 01 00:08:59 +0000 2025,4,Ini adalah tuntutan dari kami semua rakyat Ind...,1962306655817003157,https://pbs.twimg.com/media/GzuDgKjakAASSlm.jpg,NaN,in,NaN,0,1,1,https://x.com/undefined/status/196230665581700...,1257502199355076608,NaN

untuk membenarkan link url yang berubah karena Tweet-Harvest gagal mengambil Username maka perlu kita ubah menggunakan URL dasar Twitter/X seperti 
```
https://x.com/x/status/
```
kemudian di ikuti dengan data id_str seperti
```  
https://x.com/x/status/ + df['id_str']
```

## fix_link

In [14]:
import numpy as np

# Membaca file CSV
df = pd.read_csv(file_path, delimiter=",")

# Memperbaiki URL yang mengandung 'undefined'
df['tweet_url'] = np.where(
    df['tweet_url'].str.contains('undefined', na=False),
    'https://x.com/anyuser/status/' + df['id_str'].astype(str),
    df['tweet_url']
)

# Menghapus kolom username dan location
df = df.drop(columns=['location', 'username']) # Hapus kolom yang tidak diperlukan

# Menyimpan hasil ke file CSV baru
df.to_csv('tweets-data/TUNTUTAN_RAKYAT_fix.csv', index=False)
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,quote_count,reply_count,retweet_count,tweet_url,user_id_str
0,1963752713256395127,Thu Sep 04 23:55:06 +0000 2025,0,Dari sekian banyak bahasan 17+8 tuntutan rakya...,1963752713256395127,NaN,NaN,in,0,0,0,https://x.com/anyuser/status/1963752713256395127,1059593600
1,1963751829935993247,Thu Sep 04 23:51:35 +0000 2025,2,Hari ini deadline 17+8 tuntutan rakyat #KawalS...,1963751829935993247,NaN,NaN,in,0,0,0,https://x.com/anyuser/status/1963751829935993247,1856170626563891200
2,1963744711740686806,Thu Sep 04 23:23:18 +0000 2025,16,ngerayain ultah pas deadline indo dengan tuntu...,1963744711740686806,https://pbs.twimg.com/media/G0CfZv5acAEyS2M.jpg,NaN,in,2,57,0,https://x.com/anyuser/status/1963744711740686806,1868280869448003584
3,1963741023383032065,Thu Sep 04 23:08:39 +0000 2025,2,17+8 itu apa toh? Ini bener ya? Kok gak ada 'a...,1963741023383032065,NaN,NaN,in,0,1,0,https://x.com/anyuser/status/1963741023383032065,57574639
4,1963630999398404450,Thu Sep 04 23:02:35 +0000 2025,0,@imwinteoa Ini tanda tangan bahwa dokumen yg b...,1963739496064888995,NaN,imwinteoa,in,0,0,0,https://x.com/anyuser/status/1963739496064888995,1603283936091656192
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,1962314858860511538,Mon Sep 01 00:41:35 +0000 2025,0,17 + 8 tuntutan rakyat itu tadi lewat English ...,1962314858860511538,NaN,NaN,in,0,1,0,https://x.com/anyuser/status/1962314858860511538,4894329029
1023,1962313342175105389,Mon Sep 01 00:35:33 +0000 2025,89,17 + 8 TUNTUTAN RAKYAT Bukan sekadar angka tap...,1962313342175105389,https://pbs.twimg.com/media/GzuJlK5bgAAkzUP.jpg,NaN,in,1,2,91,https://x.com/anyuser/status/1962313342175105389,1864173068589125633
1024,1962310269100855772,Mon Sep 01 00:23:20 +0000 2025,2,my birthday wish? 17 + 8 tuntutan rakyat terwu...,1962310269100855772,NaN,NaN,in,0,0,0,https://x.com/anyuser/status/1962310269100855772,1839985636759220224
1025,1962309546778763713,Mon Sep 01 00:20:28 +0000 2025,1,17 + 8 Tuntutan Rakyat @prabowo kapan lagi dib...,1962309546778763713,https://pbs.twimg.com/media/GzuGH-naUAA9_4_.jpg,NaN,in,0,1,1,https://x.com/anyuser/status/1962309546778763713,1676397814920925187
1026,1962306655817003157,Mon Sep 01 00:08:59 +0000 2025,4,Ini adalah tuntutan dari kami semua rakyat Ind...,1962306655817003157,https://pbs.twimg.com/media/GzuDgKjakAASSlm.jpg,NaN,in,0,1,1,https://x.com/anyuser/status/1962306655817003157,1257502199355076608

Crosscek jumlah data yang di dapat
===

In [13]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 1027.